---
  extends:
    - plugin:react/recommended
  env:
    browser: true
    node: true
    es6: true

  parserOptions:
   ecmaVersion: 6
   sourceType: "module"
   ecmaFeatures:
    jsx: true
    spread: true
    experimentalObjectRestSpread: true

  globals:
    __DEV__: true
    __SERVER__: true
    TimelineLite: true
    FB: true
    Quad: true
    Quart: true
    Cubic: true
    Howl: true
    # tests
    describe: true
    beforeEach: true
    afterEach: true
    it: true
    expect: true

  plugins:
    - react

  rules:
    no-warning-comments:
    - warn
    - terms:
      - todo
      - fixme
      - hack
      location: anywhere
    react/no-typos: off # TODO error (plugin broken on vscode?)
    react/jsx-uses-react: error
    react/jsx-uses-vars: error
    react/jsx-no-duplicate-props: error
    react/no-deprecated: warn # TODO error
    react/prop-types:
      - warn
      - ignore:
        - children
    react/prefer-es6-class: error
    react/no-find-dom-node: warn
    react/no-direct-mutation-state: warn
    react/prefer-stateless-function: warn
    react/no-did-mount-set-state: error
    react/no-did-update-set-state: error
    react/no-will-update-set-state: off # TODO error (broken plugin ?)
    react/void-dom-elements-no-children: error
    react/no-array-index-key: off # TODO warn
    react/jsx-key: error
    react/jsx-no-comment-textnodes: error
    react/jsx-closing-bracket-location: warn
    react/self-closing-comp: warn
    react/jsx-curly-spacing:
      - warn
      - never
    react/jsx-space-before-closing:
      - warn
      - always
    react/jsx-wrap-multilines: warn
    react/jsx-boolean-value: warn
    react/no-string-refs: warn
    react/jsx-no-bind: warn
    react/require-render-return: warn
    react/sort-comp: off # TODO warn (define order)
    react/no-is-mounted: error
    react/jsx-equals-spacing: warn
    react/jsx-indent: warn
    react/jsx-indent-props: warn
    react/jsx-tag-spacing: warn
    react/jsx-max-props-per-line:
      - warn
      - maximum: 1
        when: multiline
    react/jsx-first-prop-new-line:
      - warn
      - multiline-multiprop
    curly:
      - warn
      - multi-line
    one-var:
      - warn
      - never
    no-var: warn
    prefer-const: warn
    consistent-return: off # TODO warn
    no-alert: error
    eol-last: warn
    comma-spacing: warn
    eqeqeq: error
    comma-dangle:
      - warn
      - always-multiline
    object-curly-spacing:
      - warn
      - never
    array-bracket-spacing:
      - warn
      - never
    no-cond-assign: warn
    no-console: warn
    no-constant-condition: warn
    no-control-regex: warn
    no-debugger: error
    no-dupe-args: error
    no-dupe-keys: error
    no-duplicate-case: error
    no-empty-character-class: warn
    no-empty: warn
    no-ex-assign: warn
    no-extra-boolean-cast: warn
    no-extra-parens:
      - warn
      - all
      - ignoreJSX: all
    no-extra-semi: warn
    no-func-assign: warn
    no-inner-declarations: warn
    no-invalid-regexp: error
    no-irregular-whitespace: warn
    no-negated-in-lhs: warn
    no-obj-calls: warn
    no-regex-spaces: warn
    no-sparse-arrays: warn
    no-unexpected-multiline: warn
    no-unreachable: error
    use-isnan: warn
    valid-jsdoc:
      - warn
      - requireReturn: false
        requireParamDescription: false
        requireReturnDescription: false
    valid-typeof: warn
    no-redeclare: warn
    init-declarations: warn
    no-catch-shadow: warn
    no-delete-var: warn
    no-label-var: warn
    no-shadow-restricted-names: warn
    no-shadow: warn # TODO error
    no-undef-init: warn
    no-undef: error
    no-undefined: error
    no-unused-vars: error
    no-use-before-define: warn
    # no-exclusive-tests: warn
    indent:
      - warn
      - 4
      - SwitchCase: 1
    semi:
      - error
      - always
    quotes:
      - error
      - single
    quote-props:
      - warn
      - as-needed
      - unnecessary: true
    jsx-quotes: warn
    no-spaced-func: warn
    key-spacing: warn
    brace-style: warn
    space-infix-ops: warn
    keyword-spacing: warn
    space-before-function-paren:
      - warn
      - anonymous: always
        named: never
        asyncArrow: never
    no-multiple-empty-lines: warn
    no-trailing-spaces: warn
    no-multi-spaces: warn
    dot-notation: warn
