export const SESSION = {
    CHECK_SESSION: 'SESSION.CHECK_SESSION',
    RECEIVE_SESSION: 'SESSION.RECEIVE_SESSION',
    DISCONNECT: 'SESSION.DISCONNECT',
};

export const UI = {
    ACTIVATE_PANEL: 'UI.ACTIVATE_PANEL',
    CLOSE_EDITOR: 'UI.CLOSE_EDITOR',
};

export const I18N = {
    CHANGE_LANGUAGE: 'I18N.CHANGE_LANGUAGE',
};

export const CORE = {
    ROUTE_CHANGE: 'CORE.ROUTE_CHANGE',
};

export const DATA = {
    ITEMS_SEARCH: 'DATA.ITEMS_SEARCH',
    ITEMS_RECEIVE: 'DATA.ITEMS_RECEIVE',
    USERS_SEARCH: 'DATA.USERS_SEARCH',
    USERS_RECEIVE: 'DATA.USERS_RECEIVE',
    SPACES_SEARCH: 'DATA.SPACES_SEARCH',
    SPACES_RECEIVE: 'DATA.SPACES_RECEIVE',
    CATEGORIES_SEARCH: 'DATA.CATEGORIES_SEARCH',
    CATEGORIES_RECEIVE: 'DATA.CATEGORIES_RECEIVE',
    TIMES_UPDATE: 'DATA.TIMES_UPDATE',
};

export const FORM = {
    CHANGE_FIELD: 'FORM.CHANGE_FIELD',
};
