export const SESSION = {
    CHECK_SESSION: 'SESSION.CHECK_SESSION',
    RECEIVE_SESSION: 'SESSION.RECEIVE_SESSION',
    DISCONNECT: 'SESSION.DISCONNECT',
};

export const UI = {
    ACTIVATE_PANEL: 'UI.ACTIVATE_PANEL',
    CLOSE_PANEL: 'UI.CLOSE_PANEL',
};
