export const SESSION = {
    CHECK_SESSION: 'SESSION.CHECK_SESSION',
    RECEIVE_SESSION: 'SESSION.RECEIVE_SESSION',
    DISCONNECT: 'SESSION.DISCONNECT',
};

export const UI = {
    ACTIVATE_PANEL: 'UI.ACTIVATE_PANEL',
    CLOSE_EDITOR: 'UI.CLOSE_EDITOR',
};

export const I18N = {
    CHANGE_LANGUAGE: 'I18N.CHANGE_LANGUAGE',
};

export const CORE = {
    ROUTE_CHANGE: 'CORE.ROUTE_CHANGE',
};
